version: "3"
services:
  dl_spot: 
    build: .
    ports: 
      - 5001:5000
    networks:
      dl_spot_net:
        ipv4_address: 172.19.0.44

networks:
  dl_spot_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24